version: '3'

vars:
  DEVBOX_DIR_PATH: "~/.local/share/devbox/global/default"

tasks:
  default:
    cmds:
      - task help
    silent: true

  help:
    cmds:
      - echo "Welcome to my project - maintainer<Tommy Tran Duc Thang> - email<tommytran.dev@gmail.com>"
      - echo "Run task <task_name> to run predefined script"
      - echo ""
      - echo "For setting up the environment            task local:install"
      - echo ""
      - task -l
    silent: true

  setup:
    desc: install the environment, setup env for macOS and Ubuntu
    cmds:
      - command -v devbox &> /dev/null || { curl -fsSL https://get.jetify.com/devbox | bash; }
      - cp -f ./devbox.json {{.DEVBOX_DIR_PATH}}/devbox.json
      - cp -f ./devbox.lock {{.DEVBOX_DIR_PATH}}/devbox.lock
      - devbox global install 
    silent: true

